version: '3.6'

services:
  pgsql:
    image: postgres:15-alpine
    container_name: pgsql
    hostname: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: funstack
    healthcheck:
      test: ["CMD", "pg_isready -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - intranet

  funstack:
    image: ghcr.io/riipandi/funstack:latest
    container_name: funstack
    hostname: funstack
    ports:
      - 9090:9090
    env_file: .env.docker
    networks:
      - intranet
    depends_on:
      - pgsql

networks:
  intranet:
    driver: bridge

volumes:
  pg_data:
    driver: local
